# Be sure to change these!
base_url = "https://pawroman.github.io/zola-theme-terminimal"
title = "zxen | blog"
theme = "terminimal-zxenmod"

# Sass compilation is required
compile_sass = true

# Optional: enable tags
taxonomies = [
    {name = "tags"}
]

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]

# One of: blue, green, orange, pink, red.
# Defaults to blue.
accent_color = "green"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "blue"

# The logo text - defaults to "Terminimal theme"
logo_text = "zxen / blog"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
copyright_html = "<a href=https://zxen-xi.github.io>zxen</a> | SSG: Zola | theme: terminimal (modified)"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "/blog", url = "$BASE_URL"},

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "/tags", url = "$BASE_URL/tags"},
    {name = "/archive", url = "$BASE_URL/archive"},
    {name = "/about me", url = "https://zxen-xi.github.io", newtab = true},

    # set newtab to true to make the link open in new tab
    {name = ".github()", url = "https://github.com/zxen-xi", newtab = true},
]

# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Read more."

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"

# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "main_only"
